In [116]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [43]:
dataset = pd.read_csv('heart_attack_prediction_dataset.csv')

In [44]:
dataset = dataset.drop(columns = ['Patient ID' ,'Blood Pressure' , 'Sedentary Hours Per Day' ,'BMI' , 'Country' , 'Continent' , 'Hemisphere' , 'Diet' ,'Exercise Hours Per Week' , 'Income'] ,axis =1)

In [45]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [46]:
len(X),len(y)

(8763, 8763)

In [47]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [48]:
X[1]

array([21, 1, 389, 98, 1, 1, 1, 1, 1, 1, 0, 1, 235, 1, 7], dtype=object)

In [49]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   Age                              8763 non-null   int64 
 1   Sex                              8763 non-null   object
 2   Cholesterol                      8763 non-null   int64 
 3   Heart Rate                       8763 non-null   int64 
 4   Diabetes                         8763 non-null   int64 
 5   Family History                   8763 non-null   int64 
 6   Smoking                          8763 non-null   int64 
 7   Obesity                          8763 non-null   int64 
 8   Alcohol Consumption              8763 non-null   int64 
 9   Previous Heart Problems          8763 non-null   int64 
 10  Medication Use                   8763 non-null   int64 
 11  Stress Level                     8763 non-null   int64 
 12  Triglycerides                    8

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [111]:
import tensorflow as tf
ann = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])
from tensorflow.keras.optimizers import Adam

optimizer = Adam(learning_rate=0.001)
ann.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

class_weights = {0: 1.0, 1: 2.0}  # Adjust weights as needed
history=model.fit(X_train, y_train, class_weight=class_weights, epochs=100, batch_size=32)



Epoch 1/100


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


220/220 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.4456 - loss: 0.9452
Epoch 2/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4776 - loss: 0.9330
Epoch 3/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4680 - loss: 0.9292
Epoch 4/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4944 - loss: 0.9242
Epoch 5/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5048 - loss: 0.9256
Epoch 6/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5318 - loss: 0.9127
Epoch 7/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5379 - loss: 0.9110
Epoch 8/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5618 - loss: 0.9028
Epoch 9/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5487 - loss: 0.9003
Epoch 10/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5610 - loss: 0.8905
Epoch 11/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5592 - loss: 0.8887
Epoch 12/100
220/220 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [113]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.9)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
loss, accuracy = ann.evaluate(X_test, y_test)
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy:.4f}')

55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 1]
 [0 1]
 [0 0]
 ...
 [1 0]
 [0 1]
 [1 0]]
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5261 - loss: 1.5000
Test Loss: 1.4059
Test Accuracy: 0.5368


In [114]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[819 295]
 [446 193]]


0.5772960638904735

In [117]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   Age                              8763 non-null   int64 
 1   Sex                              8763 non-null   object
 2   Cholesterol                      8763 non-null   int64 
 3   Heart Rate                       8763 non-null   int64 
 4   Diabetes                         8763 non-null   int64 
 5   Family History                   8763 non-null   int64 
 6   Smoking                          8763 non-null   int64 
 7   Obesity                          8763 non-null   int64 
 8   Alcohol Consumption              8763 non-null   int64 
 9   Previous Heart Problems          8763 non-null   int64 
 10  Medication Use                   8763 non-null   int64 
 11  Stress Level                     8763 non-null   int64 
 12  Triglycerides                    8

In [118]:

print(ann.predict(sc.transform([[67,	1	,208,72	,0,0,1,0,0,	0	,0,9,	286,	0	,6]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[[False]]
